version: 0.2
phases:
  install:
    commands:
      - ls -lha
      - printenv
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-2 --no-include-email)
  build:
    commands:
      - echo Building Docker Image...
      - docker build -t anthony-ecr-repo .
      - docker tag anthony-ecr-repo:latest 842337631775.dkr.ecr.us-east-2.amazonaws.com/anthony-ecr-repo:latest
  post_build:
    commands:
      - docker push 842337631775.dkr.ecr.us-east-2.amazonaws.com/anthony-ecr-repo:latest
