version: 0.2
phases:
  install:
    commands:
      - ls -lha
      - printenv
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-2 --no-include-email)
      # - REPOSITORY_URI=842337631775.dkr.ecr.us-east-2.amazonaws.com/anthony-ecr-repo
      # - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      # - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Building Docker Image...
      - docker build -t anthony-ecr-repo .
      - docker tag anthony-ecr-repo:latest 842337631775.dkr.ecr.us-east-2.amazonaws.com/anthony-ecr-repo:latest
  post_build:
    commands:
      - docker push 842337631775.dkr.ecr.us-east-2.amazonaws.com/anthony-ecr-repo:latest
